export enum ApiUrls {
  AUTH_LOGIN = "/auth/login",
  AUTH_ME = "/auth/me",
  USERS_ME = "/users/me",
  PROFILE = "/profile",
  RESUME = "/resume",
  RESUME_ITEMS = "/resume/items",
  RESUME_ITEM_DETAIL = "/resume/items/:id",
  BLOG_POSTS = "/blog",
  BLOG_ADMIN = "/blog/admin",
  BLOG_TAGS = "/blog/tags",
  BLOG_POST_DETAIL = "/blog/:id",
  CONTACT_SUBMIT = "/public/contact",
  CONTACT_INBOX = "/contact",
  CONTACT_MESSAGE_DETAIL = "/contact/:id",
  CONTACT_LINKS = "/contact/links",
  CONTACT_LINK_DETAIL = "/contact/links/:id",
  DASHBOARD_OVERVIEW = "/dashboard/overview",
  DASHBOARD_SNAPSHOT = "/dashboard/snapshot",
  PROJECTS_LIST = "/projects",
  PROJECT_DETAIL = "/projects/:id",
}
