export enum QueryKeys {
  AUTH_ME = "auth_me",
  PROFILE = "profile",
  RESUME = "resume",
  RESUME_ITEMS = "resume_items",
  BLOG_POSTS = "blog_posts",
  BLOG_ADMIN = "blog_admin",
  BLOG_TAGS = "blog_tags",
  BLOG_POST_DETAIL = "blog_post_detail",
  CONTACT_LINKS = "contact_links",
  CONTACT_INBOX = "contact_inbox",
  DASHBOARD_OVERVIEW = "dashboard_overview",
  DASHBOARD_SNAPSHOT = "dashboard_snapshot",
  PROJECTS_LIST = "projects_list",
  PROJECT_DETAIL = "project_detail",
}
